### ISSUE TITLE
Fails to initialize when settings module resides outside of project

### ISSUE THREAD

**Issue by akabos** [jgorset/django-kronos#42]
```
$ DJANGO_SETTINGS_MODULE=local_settings ./manage.py runserver
Traceback (most recent call last):
  File "./manage.py", line 11, in <module>
    execute_from_command_line(sys.argv)
  File "[...]/lib/python2.7/site-packages/django/core/management/__init__.py", line 385, in execute_from_command_line
    utility.execute()
  File "[...]/lib/python2.7/site-packages/django/core/management/__init__.py", line 354, in execute
    django.setup()
  File "[...]/lib/python2.7/site-packages/django/__init__.py", line 21, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "[...]/lib/python2.7/site-packages/django/apps/registry.py", line 85, in populate
    app_config = AppConfig.create(entry)
  File "[...]/lib/python2.7/site-packages/django/apps/config.py", line 87, in create
    module = import_module(entry)
  File "[...]/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/Users/akabos/Projects/@virtualenvs/rentals/lib/python2.7/site-packages/kronos/__init__.py", line 5, in <module>
    from kronos.settings import PROJECT_MODULE, KRONOS_PYTHON, KRONOS_MANAGE, \
  File "[...]/lib/python2.7/site-packages/kronos/settings.py", line 9, in <module>
    PROJECT_MODULE = sys.modules['.'.join(settings.SETTINGS_MODULE.split('.')[:-1])]
KeyError: ''
```

**Comment by vahidm** [comment]
I'm having the same problem.

**Comment by jgorset** [comment]
Hey @akabos and @vahidm, and sorry you're having this issue! I'm not using Django at the moment and so I don't really really have an incentive to scratch this itch, but I'd be super happy to accept a pull request that fixes it! :smile:

**Comment by jgorset** [comment]
Fixed!
