### ISSUE TITLE
'NoArgsCommand' is removed in Django 1.10

### ISSUE THREAD

**Issue by pawelad** [jgorset/django-kronos#53]
`NoArgsCommand` is removed in newest Django release (1.10) which makes `django-kronos` unusable:

```
$ python manage.py showtasks
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/.../lib/python3.4/site-packages/django/core/management/__init__.py", line 367, in execute_from_command_line
    utility.execute()
  File "..../lib/python3.4/site-packages/django/core/management/__init__.py", line 359, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File ".../lib/python3.4/site-packages/django/core/management/base.py", line 305, in run_from_argv
    self.execute(*args, **cmd_options)
  File ".../lib/python3.4/site-packages/django/core/management/base.py", line 356, in execute
    output = self.handle(*args, **options)
  File ".../lib/python3.4/site-packages/kronos/management/commands/showtasks.py", line 9, in handle
    kronos.load()
  File ".../lib/python3.4/site-packages/kronos/__init__.py", line 43, in load
    load_command_class(app, cmd)
  File ".../lib/python3.4/site-packages/django/core/management/__init__.py", line 40, in load_command_class
    module = import_module('%s.management.commands.%s' % (app_name, name))
  File ".../lib/python3.4/importlib/__init__.py", line 109, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 2254, in _gcd_import
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1200, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1129, in _exec
  File "<frozen importlib._bootstrap>", line 1471, in exec_module
  File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_removed
  File ".../lib/python3.4/site-packages/kronos/management/commands/installtasks.py", line 1, in <module>
    from django.core.management.base import NoArgsCommand
ImportError: cannot import name 'NoArgsCommand'
```

Quickly looking at the [docs][no args command] and the [source][source] i think it should be pretty easy to fix. I could try to tackle it and do a PR if you're busy.

[no args command]: https://docs.djangoproject.com/en/1.9/howto/custom-management-commands/#django.core.management.NoArgsCommand
[source]: https://github.com/jgorset/django-kronos/search?utf8=%E2%9C%93&q=NoArgsCommand

**Comment by jgorset** [comment]
That would be much appreciated, @pawelad! Thanks!

**Comment by pawelad** [comment]
PR merged - while waiting for release a workaround should be:
```
$ pip install --upgrade git+ssh://git@github.com:jgorset/django-kronos.git
```

**Comment by pawelad** [comment]
@jgorset what do you think about releasing a new version? I think that compatibility with the latest Django version is a reason good enough ; )

**Comment by jgorset** [comment]
Yeah, sure!

**Comment by jgorset** [comment]
How's 1.0, even? :wink:

**Comment by pawelad** [comment]
It definitely has a nice ring to it : )
