### ISSUE TITLE
ImportError: cannot import name 'gen_filenames' from 'django.utils.autoreload'

### ISSUE THREAD

**Issue by FreakyTea** [jgorset/django-kronos#65]
Hi,

i tried using your module in a business app. I run in the following error whenever i try using `runtask` or `showtasks`:

`python rms/manage.py showtasks
Traceback (most recent call last):
  File "rms/manage.py", line 15, in <module>
    execute_from_command_line(sys.argv)
  File "/path_to_project/.virtualenv/django-rms/lib/python3.7/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/path_to_project/.virtualenv/django-rms/lib/python3.7/site-packages/django/core/management/__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/path_to_project/.virtualenv/django-rms/lib/python3.7/site-packages/django/core/management/base.py", line 323, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/path_to_project/.virtualenv/django-rms/lib/python3.7/site-packages/django/core/management/base.py", line 364, in execute
    output = self.handle(*args, **options)
  File "/path_to_project/.virtualenv/django-rms/lib/python3.7/site-packages/kronos/management/commands/showtasks.py", line 9, in handle
    kronos.load()
  File "/path_to_project/.virtualenv/django-rms/lib/python3.7/site-packages/kronos/__init__.py", line 43, in load
    load_command_class(app, cmd)
  File "/path_to_project/.virtualenv/django-rms/lib/python3.7/site-packages/django/core/management/__init__.py", line 36, in load_command_class
    module = import_module('%s.management.commands.%s' % (app_name, name))
  File "/path_to_project/.virtualenv/django-rms/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/path_to_project/.virtualenv/django-rms/lib/python3.7/site-packages/django_extensions/management/commands/runserver_plus.py", line 17, in <module>
    from django.utils.autoreload import gen_filenames
ImportError: cannot import name 'gen_filenames' from 'django.utils.autoreload' (/path_to_project/.virtualenv/django-rms/lib/python3.7/site-packages/django/utils/autoreload.py)
`

Do you know what i could try to solve this?

**Comment by FreakyTea** [comment]
Little Update - installed `kronos` and removed it again (after other issues) now i'm getting:

`AttributeError: module 'kronos' has no attribute 'load'`

**Comment by jgorset** [comment]
Sorry for not getting to this a very long time ago. Closing due to old age, but feel free to reopen the issue or make a pull request if you'd still like to fix it.
